C:\3d_reconstruction>python -m pytest 1.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\3d_reconstruction
collected 0 items

=============================================== no tests ran in 13.36s ================================================

C:\3d_reconstruction>python -m pytest data_wrangling.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\3d_reconstruction
collected 0 items

================================================ no tests ran in 8.22s ================================================

C:\3d_reconstruction>python -m pytest exploratory_data_analysis
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\3d_reconstruction
collected 0 items

================================================ no tests ran in 0.02s ================================================
ERROR: file or directory not found: exploratory_data_analysis


C:\3d_reconstruction>python -m pytest exploratory_data_analysis.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\3d_reconstruction
collected 0 items

========================================== no tests ran in 94.53s (0:01:34) ===========================================

C:\3d_reconstruction>python -m pytest model_selection_binary_classifiaction(running).py
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\3d_reconstruction
collected 0 items

================================================== warnings summary ===================================================
..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\linear_model\_logistic.py:764
..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\linear_model\_logistic.py:764
  C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
  STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

  Increase the number of iterations (max_iter) or scale the data as shown in:
      https://scikit-learn.org/stable/modules/preprocessing.html
  Please also refer to the documentation for alternative solver options:
      https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
    extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\metrics\_classification.py:1221
..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\metrics\_classification.py:1221
  C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
    _warn_prf(average, modifier, msg_start, len(result))

..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\metrics\_classification.py:1221
..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\metrics\_classification.py:1221
  C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
    _warn_prf(average, modifier, msg_start, len(result))

..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\svm\_base.py:977
..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\svm\_base.py:977
  C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
    "the number of iterations.", ConvergenceWarning)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================== 8 warnings in 285.96s (0:04:45) ===========================================

C:\3d_reconstruction>python -m pytest model_selection_regression.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\3d_reconstruction
collected 0 items

================================================== warnings summary ===================================================
..\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\model_selection\_split.py:297
  C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\model_selection\_split.py:297: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
    FutureWarning

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================= 1 warning in 44.69s =================================================
